---
title: 'Reproducible Research: Peer Assessment 1'
author: "Chris M."
date: "3/14/2018"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r Loading, echo=TRUE}
library(dplyr)
library(lattice)
data=read.csv("activity.csv")
```

## What is mean total number of steps taken per day?
```{r Mean_steps_per_day, echo=TRUE}
daily=group_by(data,date)
numsteps=summarize(daily,sum(steps,na.rm=TRUE))
str(numsteps)
summary(numsteps)
plot(numsteps,type="h",xlab="Date",ylab="Number of steps")
lines(numsteps,type="h",lwd=7)
```


## What is the average daily activity pattern?
```{r Daily_Activity, echo=TRUE}
activity=group_by(data,interval)
avg_act=summarize(activity,mean(steps,na.rm=TRUE))
plot(avg_act,type='l',lwd=2,xlab="Time Interval",ylab="Average # of Steps")

max_steps=max(avg_act)
max_location=which.max(avg_act$`mean(steps, na.rm = TRUE)`)
max_interval=avg_act$interval[max_location]

cat("The maximum interval in the average activity is at interval",max_interval,"with a value of",max_steps)
```

## Imputing missing values
```{r Imputing_Missing_Values,echo=TRUE}
num_nas=sum(is.na(data$steps))
cat("There are",num_nas,"NAs in the dataset")

where_na=which(is.na(data$steps))
intervals=data$interval[where_na]
values=0
count=1
for (i in intervals) {
  values[count]=avg_act$`mean(steps, na.rm = TRUE)`[avg_act$interval==i]
  count=count+1
}

data_impute=data
data_impute$steps[where_na]=values

daily_imputed=group_by(data_impute,date)
numsteps_imputed=summarize(daily_imputed,sum(steps,na.rm=TRUE))
str(numsteps_imputed)
summary(numsteps_imputed)
plot(numsteps_imputed,type="h",xlab="Date",ylab="Number of steps")
lines(numsteps_imputed,type="h",lwd=7)
```

Imputing the data with the mean values raised the values of all the statistics.

## Are there differences in activity patterns between weekdays and weekends?

```{r Weekdays-Weekends,echo=TRUE}
data2=data_impute
data2$dayofweek=weekdays(as.Date(data$date))

data2$weektype=NA
for (i in 1:length(data2$steps)) {
  if (data2$dayofweek[i]=='Sunday' || data2$dayofweek[i]=='Saturday') {
    data2$weektype[i]='Weekend'
  } else {
    data2$weektype[i]='Weekday'
  }
}

weeks=group_by(data2,weektype,interval)
avg_week_act=summarize(weeks,mean(steps))

xyplot(`mean(steps)` ~ interval | weektype, data=avg_week_act,type='l',layout=c(1,2),ylab="Avg # of Steps",xlab="Interval")
```